[Components with more than 1 service] Refactor DLSizeLimitManagedServiceFactory component
RenanUmV/liferay-portal pull request #50
Opened 2023-09-01 16:33 UTC by RenanUmV

2023-09-01 16:33 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-01 16:33 UTC, RenanUmV commented
ci:test:sf

2023-09-01 16:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/2705/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2705/jenkins-report.html">here</a>.</b></p>

2023-09-01 16:40 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2705/">test-portal-source-format#2705</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2705/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/RenanUmV/liferay-portal/pull/50">RenanUmV#50</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2417477201">[master] ci:test:sf - RenanUmV &gt; RenanUmV - PR#50 - 2023-09-01[09:34:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/10398/">publish-testray-report#10398</a><br/></div></div>

2023-09-01 18:59 UTC, RenanUmV commented
ci:test:sf

2023-09-01 19:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/3891/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3891/jenkins-report.html">here</a>.</b></p>

2023-09-01 19:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cfdd0b8eb237264fa2825d0148d02edc305dc5a1">cfdd0b8eb237264fa2825d0148d02edc305dc5a1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RenanUmV/liferay-portal/tree/LPS-195086">LPS-195086</a><br/>Branch GIT ID: <a href="https://github.com/RenanUmV/liferay-portal/commit/42e466342cbd83ab4d8be2b4f08c7229036b8c7e">42e466342cbd83ab4d8be2b4f08c7229036b8c7e</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3891/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3891/jenkins-report.html">here</a>.</h5><pre>     [java]   at com.liferay.source.formatter.checkstyle.check.BaseCheck.visitToken(BaseCheck.java:87)
     [java]   at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:342)
     [java]   at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:449)
     [java]   at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:283)
     [java]   at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:161)
     [java]   at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
     [java]   at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
     [java]   at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
     [java]   ... 13 more
     [java] Caused by: java.lang.ClassNotFoundException: com.liferay.portal.kernel.service.UserLocalServiceUtil
     [java]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [java]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java]   at sun.misc.Launcher\$AppClassLoader.loadClass(Launcher.java:331)
     [java]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java]   ... 31 more
[stopwatch] [run.batch.test.action: 1:03.651 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:504: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-39/job/test-portal-source-format/3891//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230901120221447.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230901120221447.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1301582659.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1890329806</pre></details></html>

2023-09-01 19:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3891/">test-portal-source-format#3891</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3891/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/RenanUmV/liferay-portal/pull/50">RenanUmV#50</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2417588890">[master] ci:test:sf - RenanUmV &gt; RenanUmV - PR#50 - 2023-09-01[11:59:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/14509/">publish-testray-report#14509</a><br/></div></div>

2023-09-01 19:06 UTC, RenanUmV commented
ci:test:sf

2023-09-01 19:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/2708/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2708/jenkins-report.html">here</a>.</b></p>

2023-09-01 19:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/cfdd0b8eb237264fa2825d0148d02edc305dc5a1">cfdd0b8eb237264fa2825d0148d02edc305dc5a1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RenanUmV/liferay-portal/tree/LPS-195086">LPS-195086</a><br/>Branch GIT ID: <a href="https://github.com/RenanUmV/liferay-portal/commit/42e466342cbd83ab4d8be2b4f08c7229036b8c7e">42e466342cbd83ab4d8be2b4f08c7229036b8c7e</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2708/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2708/jenkins-report.html">here</a>.</h5><pre>     [java]   at com.liferay.source.formatter.checkstyle.check.BaseCheck.visitToken(BaseCheck.java:87)
     [java]   at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:342)
     [java]   at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:449)
     [java]   at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:283)
     [java]   at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:161)
     [java]   at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
     [java]   at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:329)
     [java]   at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:291)
     [java]   ... 13 more
     [java] Caused by: java.lang.ClassNotFoundException: com.liferay.portal.kernel.service.UserLocalServiceUtil
     [java]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [java]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java]   at sun.misc.Launcher\$AppClassLoader.loadClass(Launcher.java:331)
     [java]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java]   ... 31 more
[stopwatch] [run.batch.test.action: 1:04.045 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:504: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-40/job/test-portal-source-format/2708//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230901121006047.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230901121006047.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1591874060.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null69202702</pre></details></html>

2023-09-01 19:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2708/">test-portal-source-format#2708</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2708/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/RenanUmV/liferay-portal/pull/50">RenanUmV#50</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2417589133">[master] ci:test:sf - RenanUmV &gt; RenanUmV - PR#50 - 2023-09-01[12:06:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/10404/">publish-testray-report#10404</a><br/></div></div>

2023-09-04 17:41 UTC, rafaprax requested changes

2023-09-04 17:41 UTC, rafaprax commented on modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/configuration/admin/service/DLSizeLimitManagedServiceFactory.java
> +@Component(service = ManagedServiceFactory.class)
you forgot the servicePid property

2023-09-04 17:41 UTC, rafaprax commented on modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/configuration/helper/DLSizeLimitConfigurationHelper.java
> +	property = Constants.SERVICE_PID + "=com.liferay.document.library.internal.configuration.DLSizeLimitConfiguration.scoped",
property = Constants.SERVICE_PID + "=com.liferay.document.library.internal.configuration.DLSizeLimitConfiguration.scoped" is not required here.

2023-09-04 17:41 UTC, rafaprax commented on modules/apps/document-library/document-library-test/src/testIntegration/java/com/liferay/document/library/internal/configuration/admin/service/test/DLSizeLimitManagedServiceFactoryTest.java
> +			_getDLSizeLimitConfigurationHelper().getClass(),
avoid chaining

2023-09-04 17:41 UTC, rafaprax commented on modules/apps/document-library/document-library-service/src/test/java/com/liferay/document/library/internal/util/DLValidatorImplTest.java
> +		_dlSizeLimitConfigurationHelper = Mockito.mock(
create the mock when creating the field.

2023-09-04 17:41 UTC, rafaprax commented on modules/apps/document-library/document-library-service/src/test/java/com/liferay/document/library/internal/util/DLValidatorImplTest.java
> +		dlValidatorImpl.setDLSizeLimitConfigurationHelper(
sort method call

2023-09-04 18:51 UTC, rafaprax approved these changes

2023-09-04 18:51 UTC, rafaprax commented on modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/configuration/admin/service/DLSizeLimitManagedServiceFactory.java
> +				companyId);
rename to `removeCompanyConfigurationBean`

2023-09-04 18:51 UTC, rafaprax commented on modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/configuration/admin/service/DLSizeLimitManagedServiceFactory.java
> +				companyId);
call the `removeCompanyMimeTypeSizeLimitsMap` instead

2023-09-04 18:51 UTC, rafaprax commented on modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/configuration/admin/service/DLSizeLimitManagedServiceFactory.java
> +			_dlSizeLimitConfigurationHelper.removeCompanyConfigurationBeans(
Hey @RenanUmV. Please move the entire `_unmapPid` to the helper class. Thx

2023-09-04 18:51 UTC, rafaprax commented on modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/configuration/persistence/listener/DLSizeLimitConfigurationModelListener.java
> +	protected void setDLSizeLimitConfigurationHelper(
Please remove this method and use `ReflectionTestUtil` to inject the field value into the test classes.

2023-09-04 21:49 UTC, closed without merging