[Component with its own class name as service type] LPS-197370 Refactor components from lima modules part 2
RenanUmV/liferay-portal pull request #59
Opened 2023-09-26 20:55 UTC by RenanUmV

2023-09-26 20:55 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-26 20:55 UTC, RenanUmV commented
ci:test:sf

2023-09-26 20:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/4879/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4879/jenkins-report.html">here</a>.</b></p>

2023-09-26 21:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f9372b7b8b33f963988bb7155f88bdbbcc7154da">f9372b7b8b33f963988bb7155f88bdbbcc7154da</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RenanUmV/liferay-portal/tree/LPS-197370">LPS-197370</a><br/>Branch GIT ID: <a href="https://github.com/RenanUmV/liferay-portal/commit/7f74d88052802ccbee7f054ee43e0162a69ac756">7f74d88052802ccbee7f054ee43e0162a69ac756</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4879/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4879/jenkins-report.html">here</a>.</h5></details></html>

2023-09-26 21:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4879/">test-portal-source-format#4879</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4879/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/RenanUmV/liferay-portal/pull/59">RenanUmV#59</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2431783929">[master] ci:test:sf - RenanUmV &gt; RenanUmV - PR#59 - 2023-09-26[13:56:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/18512/">publish-testray-report#18512</a><br/></div></div>

2023-09-27 18:04 UTC, MrJohn1911 requested changes

2023-09-27 18:04 UTC, MrJohn1911 commented on modules/apps/knowledge-base/knowledge-base-service/src/main/java/com/liferay/knowledge/base/internal/importer/KBArticleImporter.java
> +		ConfigurationProvider configurationProvider,
hey @RenanUmV  can you check if makes more sense if you pass this reference directly in the method that uses it?

2023-09-27 19:01 UTC, closed without merging